### ISSUE TITLE
Bikeshedding: Artifact vs Artefact

### ISSUE THREAD

**Issue by carstenbauer** [JuliaMolSim/PseudoLibrary#1]
We typically use the american spelling "artifact" instead of the british "artefact", see e.g. https://pkgdocs.julialang.org/v1/artifacts/. 😄

**Comment by mfherbst** [comment]
Ach @carstenbauer :smile: ... but I assume you're right, we should change that for consistency.

**Comment by antoine-levitt** [comment]
Artifact is what magic the gathering uses so clearly we should use that as well. (it's confusing because in French it's artefact...)
