### ISSUE TITLE
PseudoDojo as git submodules

### ISSUE THREAD

**Issue by azadoks** [JuliaMolSim/PseudoLibrary#4]
The PseudoDojo guys are working/have finished putting their pseudos on github, e.g. in the repo for the [scalar-relativistic PBE family](https://github.com/PseudoDojo/ONCVPSP-PBE-SR) (there are many such repos).

We could add these as git submodules so that we don't have to host the files here and so we can avoid having stale copies lying around.

I could even ask the SSSP devs (i.e. Jusong) to do the same with their families. Slower moving things like GBRV, SG-15, and HGH can probably be safely stored here.

**Comment by mfherbst** [comment]
It seems the most up to date version is the website and not the git repo. We will soon use scripts to directly scrape them (similar to what aiida is doing).
